apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{- .Chart.Name | trunc 52 | trimSuffix "-" -}}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  egress:
    - {}
  ingress:
    - ports:
        - port: 20257
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "node-problem-detector.name" . }}
  policyTypes:
    - Egress
    - Ingress
