apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{- .Chart.Name | trunc 52 | trimSuffix "-" -}}"
  namespace: "{{ .Release.Namespace }}"
spec:
  egress:
    - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "node-problem-detector.name" . }}
  policyTypes:
    - Egress
