apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: "{{- .Chart.Name | trunc 52 | trimSuffix "-" -}}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "node-problem-detector.name" . }}
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"
  podMetricsEndpoints:
    - port: "exporter"
      interval: 60s
      scrapeTimeout: 10s
