apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: "{{- .Chart.Name | trunc 52 | trimSuffix "-" -}}-exceptions"
  namespace: "{{ .Release.Namespace }}"
spec:
  exceptions:
    - policyName: disallow-host-path
      ruleNames:
        - autogen-host-path
    - policyName: restrict-volume-types
      ruleNames:
        - autogen-restricted-volumes
    - policyName: require-run-as-nonroot
      ruleNames:
        - autogen-run-as-non-root
    - policyName: restrict-seccomp-strict
      ruleNames:
        - autogen-check-seccomp-strict
    - policyName: disallow-capabilities-strict
      ruleNames:
        - autogen-require-drop-all
    - policyName: disallow-privilege-escalation
      ruleNames:
        - autogen-privilege-escalation
    - policyName: disallow-privileged-containers
      ruleNames:
        - autogen-privileged-containers
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Pod
          namespaces:
            - "{{ .Release.Namespace }}"
          names:
            - {{ include "node-problem-detector.fullname" . }}*
