apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: "{{- .Chart.Name | trunc 52 | trimSuffix "-" -}}-exceptions"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
spec:
  exceptions:
    - policyName: disallow-host-path
      ruleNames:
        - host-path
        - autogen-host-path
    - policyName: restrict-volume-types
      ruleNames:
        - restricted-volumes
        - autogen-restricted-volumes
    - policyName: require-run-as-nonroot
      ruleNames:
        - run-as-non-root
        - autogen-run-as-non-root
    - policyName: restrict-seccomp-strict
      ruleNames:
        - check-seccomp-strict
        - autogen-check-seccomp-strict
    - policyName: disallow-capabilities-strict
      ruleNames:
        - require-drop-all
        - autogen-require-drop-all
    - policyName: disallow-privilege-escalation
      ruleNames:
        - privilege-escalation
        - autogen-privilege-escalation
    - policyName: disallow-privileged-containers
      ruleNames:
        - privileged-containers
        - autogen-privileged-containers
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Pod
          namespaces:
            - "{{ .Release.Namespace }}"
          names:
            - {{ include "node-problem-detector.fullname" . }}*
