apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{- .Chart.Name | trunc 52 | trimSuffix "-" -}}"
  namespace: "{{ .Release.Namespace }}"
spec:
  endpoints:
    - interval: 60s
      path: /metrics
      port: exporter
      scrapeTimeout: 10s
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "node-problem-detector.name" . }}
